### ISSUE TITLE
terminationGracePeriodSeconds 0 is unsafe

### ISSUE THREAD

**Issue by nvtkaszpir** [Gradiant/charts#1]
I've noticed that opentsdb uses `terminationGracePeriodSeconds: 0`, which is quite unsafe [1] and can also lead to data loss if opentsdb will not be able to flush data to the hbase backend.
I suggest to make it default or configurable.

[1] https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#deployment-and-scaling-guarantees

**Comment by cgiraldo** [comment]
Thank you! Fixed.
