### ISSUE TITLE
chart for hbase 0.1.3 not published

### ISSUE THREAD

**Issue by nvtkaszpir** [Gradiant/charts#18]
Looks like hbase 0.1.3 is not available in gh pages.

But hdfs 0.1.6 was published.

**Comment by cgiraldo** [comment]
We have some problems with helm-releaser github action. 

It seems that the action can only add one chart at a time per commit to master. I have removed hbase release 0.1.3 and created a new commit to master. 

It is fixed now.

**Comment by nvtkaszpir** [comment]
Ah, good to know.
Thanks!
