### ISSUE TITLE
OpenTSDB does not need to be statefulset

### ISSUE THREAD

**Issue by nvtkaszpir** [Gradiant/charts#25]
I don't see a reason why opentsdb needs to be a statefulset.
It's pretty stateless service because it does not store anything on the disks except temporaty graphs.

I believe it is better to convert it to a deployment with 60s graceful shutdown so it can flush data to the hbase backend.
It would also make it much easier to scale it, especially based on CPU.

**Comment by cgiraldo** [comment]
We make OpenTSDB stateful because we follow the same template as for Hdfs and Hbase Charts, but you are right, we should convert it to a deployment.

**Comment by nvtkaszpir** [comment]
AFAIR hbase master and regionserver are not stateful as of writing on disk - they forward requests to the hdfs - but it helps to keep them as stateful due to naming conventions.
