### ISSUE TITLE
labels defined in helpers are used in selectors - makes normal upgrades impossible

### ISSUE THREAD

**Issue by nvtkaszpir** [Gradiant/charts#26]
Not sure it if this is done on purpose or not.

(probably all) charts use helpers in such way that they define `helm.sh/chart`:
```
{{- define "hdfs.labels" -}}
helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
app.kubernetes.io/instance: {{ .Release.Name | quote }}
app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
app.kubernetes.io/part-of: {{ .Chart.Name }}
{{- end -}}

```
and then those labels are used in selectors for statefulsets (and actually anything else aswell).
Unfortunately kubernetes does not allow changing those and throws error in case of upgrade:

```
Error: UPGRADE FAILED: cannot patch "h-hdfs-httpfs" with kind Deployment: Deployment.apps "h-hdfs-httpfs" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/component":"httpfs", "app.kubernetes.io/instance":"h", "app.kubernetes.io/managed-by":"Helm", "app.kubernetes.io/name":"hdfs", "app.kubernetes.io/part-of":"hdfs", "app.kubernetes.io/version":"2.7.7", "helm.sh/chart":"hdfs-0.1.7"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable && cannot patch "h-hdfs-datanode" with kind StatefulSet: StatefulSet.apps "h-hdfs-datanode" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden && cannot patch "h-hdfs-namenode" with kind StatefulSet: StatefulSet.apps "h-hdfs-namenode" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden
```

Fix:
-  proper - remove `helm.sh/chart`, `app.kubernetes.io/version` and other offending labels or use different selector (stripped down to `.../managed-by`, `.../part-of`, `.../instance`) from selectors
- (workaround) use local chart but with manually changed `helm.sh/chart` version to be the same as on the current deployment

**Comment by nvtkaszpir** [comment]
ping @cgiraldo

**Comment by cgiraldo** [comment]
Hi, 
We select labels from the recommended by [Kubernetes doc](https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/#labels).

I will go for the first Fix option you propose, just removing offending labels from the selector part.

I will try to go with modifications next week, but I can't promise...

**Comment by nvtkaszpir** [comment]
I'm doing that with hadoop for now.
In general going to keep helpers `labels` and introduce `labels_selectors`. 
Unfortunately first option requires to set up hadoop stack from scratch because selectors are immutable.
