### ISSUE TITLE
Presto Chart missing?

### ISSUE THREAD

**Issue by ckdarby** [Gradiant/charts#27]
@cgiraldo Came across on helm hub a repo for prestosql by you but went to fetch and got a nice little error that the release is missing :(?

```
helm fetch gradiant/prestosql --version 0.1.0
Error: failed to fetch https://github.com/Gradiant/charts/releases/download/prestosql-0.1.0/prestosql-0.1.0.tgz : 404 Not Found
```

**Comment by cgiraldo** [comment]
Yes. The prestosql chart is a WIP that was released by mistake. It was removed by helmhub does not refresh the repository index.

I have added a [prestosql branch](https://github.com/Gradiant/charts/tree/prestosql/charts/prestosql) with the prestosql chart source. You caninstall it from source and test it. Comments are welcome!

**Comment by ckdarby** [comment]
Any reason why there isn't a catalog directory with just a basic blackhole or memory one? Is it just because the base docker container doesn't define either of these?

Were your plans to stop here mostly with what you're putting in the public chart or...?

Things I'd be interested in contributing to the chart:
- Push the metastore to AWS glue & use hadoop2 for s3 access
- Spill to disk enable option that sets up a lot of the volume kind of stuff

**Comment by cgiraldo** [comment]
There is no reason to not add a catalog directory.

We are exploring presto and begin with the presto chart, but we should discuss how to configure connectors, through external configmap? parameters in values.yaml? both? other options?

So our plans are to continue chart development yo make a functional presto chart generic enough to be useful for the community. We are interested in hive-mestastore and want to make some tests with presto+hive-metastore+hdfs before releasing the helm chart.

And of course, contributions and discussions on how to arrange the chart are very welcome.
