### ISSUE TITLE
Readiness probe failed: Get http://10.42.1.234:10002/: dial tcp 10.42.1.234:10002: connect: connection refused

### ISSUE THREAD

**Issue by xyxiaoyou** [Gradiant/charts#28]
When hive was installed by helm under k8s, hive server pod reported the following error: 
"Readiness probe failed: Get http://10.42.1.234:10002/: dial tcp 10.42.1.234:10002: connect: connection refused".
--------------logs----------
Configuring core
- Setting fs.defaultFS=hdfs://hive-hdfs-namenode:8020
Configuring hdfs
Configuring yarn
Configuring httpfs
Configuring kms
Configuring mapred
Configuring hive
Configuring for multihomed network
mkdir: Permission denied: user=root, access=WRITE, inode="/":hdfs:supergroup:drwxr-xr-x
mkdir: Permission denied: user=root, access=WRITE, inode="/":hdfs:supergroup:drwxr-xr-x
chmod: `/tmp': No such file or directory
chmod: `/user/hive/warehouse': No such file or directory
2020-05-12 05:48:56: Starting HiveServer2
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/opt/hive/lib/log4j-slf4j-impl-2.6.2.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/opt/hadoop-2.7.4/share/hadoop/common/lib/slf4j-log4j12-1.7.10.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]

**Comment by cgiraldo** [comment]
This was a bug introduced when changing hdfs chart requirement version.

It should be fixed in [hive chart v0.1.2](https://github.com/Gradiant/charts/releases/download/hive-0.1.2/hive-0.1.2.tgz).
