### ISSUE TITLE
Is there a chance to bump the version of OpenTSDB to 3.0.90-SNAPSHOT

### ISSUE THREAD

**Issue by asdf2014** [Gradiant/charts#33]

**Comment by asdf2014** [comment]
@cgiraldo PTAL

**Comment by cgiraldo** [comment]
We will support openTSDB version 3.x when It be released, for now, It is currently in development state. However, I will try  to make time for this issue, but I can't promise anything.

If you want to try, you can take the code and modify charts/opentsdb/templates/opentsdb-deployment.yaml to add a custom "command" and "args" fields that work with the OpenTSDB 3.0.90-SNAPSHOT image.
You should also adapt files at charts/opentsdb/resources/config/ to work with OpenTSDB 3.0.x.

**Comment by asdf2014** [comment]
@cgiraldo Thanks a lot. I will give a try.
