### ISSUE TITLE
Deployed the hive helm chart as is but liveness and readiness fails

### ISSUE THREAD

**Issue by ChrisTomAlx** [Gradiant/charts#34]
Hi, 
    Thanks for this great helm chart, but when I installed the helm chart without changing any of the default values hive-server would keep crashing and restarting. I used the command `helm install my-hive gradiant/hive --version 0.1.4`

### Things I have already tried

- I pinpointed the issue to liveness and readiness probes of the hive-server statefulset failing. 
- I increased resources given to hive and hive-metastore as well
- I made sure the firewall wasn't blocking any ports but still the probes fail

### Environment
- GKE
- Master version - 1.16.13-gke.401

What else can I try? Any help would be appreciated

**Comment by cgiraldo** [comment]
Hi,

This is a bug. We have change default user of hive-server from root to "hive", and permissions in hdfs /tmp folder were not updated accordingly.

**Comment by cgiraldo** [comment]
Try now with:

```
helm install my-hive gradiant/hive --version 0.1.5
```

Thanks for file the bug!

**Comment by ChrisTomAlx** [comment]
Hi @cgiraldo Thanks a lot for the quick response. 

I tried installing `0.1.5` with `helm install my-hive gradiant/hive --version 0.1.5` and now I am getting this error `Error: secrets "my-hive-postgresql" already exists`
Completely cleaned the cluster and retried as well, still ran into the same issue. Just to confirm it wasn't an issue with my cluster I installed `0.1.4` and it installed but with the same old liveness issue.

**Comment by cgiraldo** [comment]
I made a mistake with hive requirements since postgresql is already provided by hive-metastore.
I have revert hive-0.1.5 release and make a new one.
Now It should work.

Maybe you need to do a helm repo update. 

Also all pods in running state can take several minutes.

**Comment by ChrisTomAlx** [comment]
It works now. I will play around with the helm chart and raise issues if I come across any.
Thanks a lot :)))
