### ISSUE TITLE
HDFS HttpFS Authentication errors using current chart version

### ISSUE THREAD

**Issue by loicdescotte** [Gradiant/charts#40]
When I install the current chart version like this : 

`helm install hdfs gradiant/hdfs`, I am unable to use httpfs to create directories or files : 

`http://httpfs-host/webhdfs/v1/user/loic/test?op=MKDIRS&user.name=loic` gives me a 500 Internal Server Error :

```
{
"RemoteException": {
"message": "User: hdfs is not allowed to impersonate loic",
"exception": "RemoteException",
"javaClassName": "org.apache.hadoop.ipc.RemoteException"
}
}
```

However, it is working when I'm using the 0.1.0 version like this  : 

`helm install hdfs https://github.com/Gradiant/charts/releases/download/hdfs-0.1.0/hdfs-0.1.0.tgz`

**Comment by cgiraldo** [comment]
Hi loic,

There is a bug in the user impersonation configuration. We have changed the default admin user in hdfs image from `root`to `hdfs`, but we have not updated the corresponding core-site.xml configuration to let `hdfs` user to impersonate other users.

With the latest release it should work.

**Comment by loicdescotte** [comment]
Thanks for the update!
