### ISSUE TITLE
cannot copy files to hdfs: block under construction

### ISSUE THREAD

**Issue by RafalSkolasinski** [Gradiant/charts#44]
Just tried to deploy `hdfs` using your helm charts and test it using `rclone` beta client.

Unfortunately I am unable to copy over files to hdfs. Client hags and in logs I see
```
2021-01-12 11:57:06,270 INFO org.apache.hadoop.hdfs.StateChange: BLOCK* allocate blk_1073741839_1015{UCState=UNDER_CONSTRUCTION, truncateBlock=null, primaryNodeIndex=-1, replicas=[ReplicaUC[[DISK]DS-1e01efed-b1b9-40bc-adc6-0abf2ae3ca00:NORMAL:10.244.0.25:50010|RBW], ReplicaUC[[DISK]DS-ab65c535-fabb-4e29-ad48-fb15ac3665a9:NORMAL:10.244.0.23:50010|RBW], ReplicaUC[[DISK]DS-52242411-b848-490b-9b28-9de6d5ad63ff:NORMAL:10.244.0.27:50010|RBW]]} for /test-folder/test.txt
```

hdfs support issue in rclone: https://github.com/rclone/rclone/issues/42

**Comment by RafalSkolasinski** [comment]
The problem seems to be present only when coping files over to hdfs. 

To reproduce:
1. `helm install hdfs gradiant/hdfs` in the k8s cluster
2. Get beta `rclone` with hdfs support: https://beta.rclone.org/ (I used `v1.54.0-beta.5058.35a4de203`)
3.  configure rclone with
```
[hdfs-kind]
type = hdfs
namenode = localhost:8020
username = hdfs
```
4. make folder: `/usr/bin/rclone mkdir hdfs-kind:/test-folder`
5. attempt to copy over file: `/usr/bin/rclone copy test.txt hdfs-kind:/test-folder/`

**Comment by RafalSkolasinski** [comment]
Happy to provide any more info if required.

**Comment by cgiraldo** [comment]
hdfs clients must be run inside kubernetes cluster in order to be able to resolve and access datanodes pods (port-forward is not enough though).

Other option to perform operations from outside the kubernetes cluster is to call httpfs rest service.

**Comment by RafalSkolasinski** [comment]
Thank you @cgiraldo, I will try from inside the cluster and get back to you :+1:

**Comment by RafalSkolasinski** [comment]
Just tested and it works fine from inside the cluster.
