### ISSUE TITLE
Hbase Master: Permission Denied

### ISSUE THREAD

**Issue by sbbagal13** [Gradiant/charts#49]
I am getting below exception while running Hbase chart on Openshift K8S , Looks like permission issues , can anyone help me with resolution

cp: can't create '/opt/hbase-2.0.1/conf/hbase-site.xml': File exists
cp: can't create '/opt/hbase-2.0.1/conf/hbase-env.sh': File exists
running master, logging to /opt/hbase-2.0.1/bin/../logs/hbase--master-hbase-hbase-master-0.out
/opt/hbase-2.0.1/bin/hbase-daemon.sh: line 195: /opt/hbase-2.0.1/bin/../logs/hbase--master-hbase-hbase-master-0.out: Permission denied
head: /opt/hbase-2.0.1/bin/../logs/hbase--master-hbase-hbase-master-0.out: No such file or directory
running thrift, logging to /opt/hbase-2.0.1/bin/../logs/hbase--thrift-hbase-hbase-master-0.out
/opt/hbase-2.0.1/bin/hbase-daemon.sh: line 195: /opt/hbase-2.0.1/bin/../logs/hbase--thrift-hbase-hbase-master-0.out: Permission denied
head: /opt/hbase-2.0.1/bin/../logs/hbase--thrift-hbase-hbase-master-0.out: No such file or directory
Thu Jul 22 03:48:38 UTC 2021: Waiting for logs...
tail: can't open '/opt/hbase-2.0.1/logs/*': No such file or directory

**Comment by cgiraldo** [comment]
You can't modify hbase-site.xml nor hbase-env.sh in the pod. This files are mounted from the hbase configmap.
If you want to modify them, you have to edit the corresponding configmap and restart the pod (or just delete the pod and wait for de statefulset to deploy a new one):

`kubectl edit configmap RELEASE_NAME-hbase`

**Comment by sbbagal13** [comment]
Hi @cgiraldo , Thanks for responding,
I am not trying to modify above files in POD , but these exceptions are coming while deploying chart as is , without doing any changes. I am thinking its something which is because of user permissions. 
These exceptions are throwing from **hbase-configmap.yaml** while executing below code. Also at the time of starting master to create log file. 

    for f in hbase-site.xml hbase-env.sh; do
      if [[ -e ${CONFIG_DIR}/$f ]]; then
        cp ${CONFIG_DIR}/$f $HBASE_PREFIX/conf/$f
      else
        echo "ERROR: Could not find $f in $CONFIG_DIR"
        exit 1
      fi
    done

Any suggestions to add user specific info to run config map ?
