### ISSUE TITLE
[hbase] HBase master service should have clusterIP: None

### ISSUE THREAD

**Issue by nvtkaszpir** [Gradiant/charts#5]
Issue:
- let's assume the helm chart release name was set to 'steve'
- hadoop, hbase, zookeeper are deployed separately as standalone charts (not using umbrella)
- `charts/charts/hbase/templates/hbase-master-svc.yaml` defines service for hbase-master, but it does not set `.spec.clusterIP: None`
- hbase statefulset when starts then it registes in zookeeper under /hbase/master under hostname `steve-hbase-master-0.steve-hbase-master.my-ns.svc.cluster.local`
- hbase region server when connecting to zookeeper gets info about /hbase/master and tries to solve the hostname, but it fails
- in the effect hbase region server is up and running but not connected to hbase masters.

Fix:
 `charts/charts/hbase/templates/hbase-master-svc.yaml` add `clusterIp: None` under spec section:
```yaml
spec:
  clusterIP: None
```

Hbase regionserver logs:
```text
steve-hbase-regionserver-0 regionserver 2020-04-02 10:26:17,206 WARN  [regionserver/steve-hbase-regionserver-0:16020] regionserver.HRegionServer: Unable to connect to master. Retrying. Error was:
steve-hbase-regionserver-0 regionserver java.net.UnknownHostException: can not resolve steve-hbase-master-0.steve-hbase-master.data-metrics.svc.cluster.local,16000,1585809657345
steve-hbase-regionserver-0 regionserver   at org.apache.hadoop.hbase.ipc.AbstractRpcClient.createAddr(AbstractRpcClient.java:430)
steve-hbase-regionserver-0 regionserver   at org.apache.hadoop.hbase.ipc.AbstractRpcClient.createBlockingRpcChannel(AbstractRpcClient.java:507)
steve-hbase-regionserver-0 regionserver   at org.apache.hadoop.hbase.regionserver.HRegionServer.createRegionServerStatusStub(HRegionServer.java:2498)
steve-hbase-regionserver-0 regionserver   at org.apache.hadoop.hbase.regionserver.HRegionServer.reportForDuty(HRegionServer.java:2546)
steve-hbase-regionserver-0 regionserver   at org.apache.hadoop.hbase.regionserver.HRegionServer.run(HRegionServer.java:930)
steve-hbase-regionserver-0 regionserver   at java.lang.Thread.run(Thread.java:748)
```

**Comment by cgiraldo** [comment]
Thanks for pointing this and the PR! 
hbase chart 0.1.2 is now available with your fix.
