### ISSUE TITLE
[hdfs] Datanode HADOOP_IDENT_STRING and USER env var not set in containers

### ISSUE THREAD

**Issue by nvtkaszpir** [Gradiant/charts#7]
Hadoop startup script uses /opt/hadoop/sbin/hadoop-daemon.sh in bootstrap process.
hadoop-daemon.sh uses some env vars that are expected to be set (some are optional), and it tries to use default ones to define some, for example HADOOP_IDENT_STRING if not set then it falls back to USER env var.

Unfortunately in Docker USER var is not set, thus HADOOP_IDENT_STRING is set to empty string.
This means some other relying commands are failing or misbehaving:
- chown for logs dir will fail with message similar to `chown: missing operand after ‘/opt/hadoop/logs’`
- log files will be with two dashes:
```text
bash-5.0# ls -la /opt/hadoop/logs/
total 208
drwxr-xr-x 2 root root   4096 Apr  3 13:21 .
drwxr-xr-x 1 root root   4096 Apr  3 13:21 ..
-rw-r--r-- 1 root root      0 Apr  3 13:21 SecurityAuth-root.audit
-rw-r--r-- 1 root root 188934 Apr  3 17:51 hadoop--datanode-hdfs-datanode-2.log
-rw-r--r-- 1 root root    730 Apr  3 13:21 hadoop--datanode-hdfs-datanode-2.out
```

... and so on.

unfortunately, current chart implementation does not support adding custom env vars to the pods.

Fix:
There are two ways:
- quick: add to the current sts template:
```yaml
env:
  - name: HADOOP_IDENT_STRING
    value: "root"
```
- more complex - extend templates to allow passing env vars per datanode, namenode from map (for example incubating/zookeeper chart does it)
- also in the future run as non-root user

**Comment by cgiraldo** [comment]
@nvtkaszpir,
check if you still need to provide custom environment variables with the new hdfs image (it runs as non-root user `hdfs`).

**Comment by nvtkaszpir** [comment]
will look into this, just glanced over the commit https://github.com/Gradiant/dockerized-hadoop/commit/b1ccf8dcd769456b8bb46495ecfbc22696d7d05c#diff-3254677a7917c6c01f55212f86c57fbfR36

But I think it needs more tests with current helm charts and changing ownership of the files on the volumes.

**Comment by cgiraldo** [comment]
You are right. Tests does not cover persistent volumes.

I have fix problems with persistent volume permissions in #21.
