### ISSUE TITLE
Readme chart address was invalid

### ISSUE THREAD

**Issue by taoran92** [Gradiant/charts#70]
https://gradiant.github.io/bigdata-charts/ this address was 404 not found.

**Comment by cgiraldo** [comment]
This address is for a helm repository. Check [https://gradiant.github.io/bigdata-charts/index.yaml]( https://gradiant.github.io/bigdata-charts/index.yaml)

The repository does not include an index.html with information so you receive a 404, but the repository is working with helm.

For readme, just follow the information of the [github repo](https://github.com/Gradiant/bigdata-charts/blob/master/README.md).
