### ISSUE TITLE
[hdfs] setting namenode replicas to something else than 1 may lead to cluster instability

### ISSUE THREAD

**Issue by nvtkaszpir** [Gradiant/charts#8]
According to the official Hadoop docs running more than 1 namenode requires shared storage, for example nfs or running in Quorum Journal Manager. [1]

Fix:
- temporary - add comment about namenode.replicas: 1 that it should not be changed  (or drop it)
- proper -  implement running journalnodes (requires also changes in https://github.com/Gradiant/dockerized-hadoop to implement `hadoop-journalnode`, building images and publishing them) with at least 3 replicas with antiaffinity rules.

References:
[1] https://hadoop.apache.org/docs/r2.7.7/hadoop-project-dist/hadoop-hdfs/HDFSHighAvailabilityWithQJM.html

**Comment by cgiraldo** [comment]
Thanks for open issues and propose fixes. Can you provide a pull request for the temporary fix?
High availability feature can be requested in a new issue.

**Comment by nvtkaszpir** [comment]
Yeah I will provide PRs in the next week.

For now managed to get quite stable setup on GKE preemtible nodes, will see how it works over the weekend, so prepare for more issues ;-)

**Comment by nvtkaszpir** [comment]
This is already fixed in https://github.com/Gradiant/charts/commit/f44c47597b6837129daba881106e92997ce40275
